### PR TITLE
Merge many_trees into master

### PR DESCRIPTION
**Pull request by kloppstock**
Finalizes the project and adds teh btree type to the master.

### CODE REVIEW

**Comment by de-narm** [comment]
I've already looked into everything concering my code and I'm d'accord with this merge.

**Comment by kloppstock** [comment]
My code should also work after the merge. 
@arbu is your code on this branch complete and working?

**Comment by arbu** [comment]
It's working. I just removed an unused field and now I'm not quiet sure what to do with the one-field-struct. It looks a bit strange, but converting it to a pointer of a pointer means reworking the whole code. Besides that it's done.

**Comment by kloppstock** [comment]
I will leave it that way, merge and send the code to our supervisor.

**Pull request merged**
